
# NumPy &amp; PyTorch: Introduction

Authors: Khanh Vu (UCI), Duc Hoang (MIT), Trinh Chau, Thien Bui, Trung Pham, Minh Duc. Adapted from: Mathieu Blondel.

# 1. Introduction / Giới thiệu

**NumPy** is the foundational library for numerical computing in Python. It provides the `ndarray` — a fast, memory-efficient multi-dimensional array — and a rich collection of mathematical operations.

**PyTorch** is a deep learning framework developed by Meta AI. Its core data structure is the **Tensor**, which is conceptually modeled after NumPy's `ndarray`. Almost every NumPy operation has a direct PyTorch equivalent with the same name and behavior.

However, PyTorch tensors add two game-changing capabilities for deep learning:

1. **GPU acceleration** — tensors can be moved to a GPU (`.to('cuda')`) for 10–100× speedups on large computations.
2. **Automatic differentiation (Autograd)** — PyTorch automatically tracks operations and computes gradients, which is the engine that trains neural networks.

> If you know NumPy, you already know ~80% of PyTorch's tensor API.

**NumPy** là thư viện nền tảng cho tính toán số học trong Python. Nó cung cấp `ndarray` — một mảng đa chiều nhanh và tiết kiệm bộ nhớ — cùng với một bộ sưu tập phong phú các phép toán.

**PyTorch** là một framework deep learning được phát triển bởi Meta AI. Cấu trúc dữ liệu cốt lõi của nó là **Tensor**, được thiết kế dựa trên `ndarray` của NumPy. Hầu như mọi thao tác trong NumPy đều có một hàm tương đương trong PyTorch với cùng tên và cách hoạt động.

Tuy nhiên, tensor PyTorch bổ sung hai khả năng đột phá cho deep learning:

1. **Tăng tốc GPU** — tensor có thể được di chuyển lên GPU (`.to('cuda')`) để tăng tốc 10–100× cho các tính toán lớn.
2. **Tự động vi phân (Autograd)** — PyTorch tự động theo dõi các phép toán và tính đạo hàm, đây chính là động cơ huấn luyện mạng nơ-ron.

> Nếu bạn đã biết NumPy, bạn đã biết khoảng 80% API tensor của PyTorch.

To use NumPy and PyTorch, import them as follows:

Để sử dụng NumPy và PyTorch, hãy nhập chúng như sau:

In [1]:
import numpy as np
import torch


## 2. Array / Tensor creation — Tạo mảng / Tạo Tensor

### 2.1 From Python lists / Từ danh sách Python

**NumPy:** arrays can be created from Python lists using `np.array`.

**NumPy:** mảng có thể được tạo từ danh sách Python bằng `np.array`.

In [6]:
# NumPy
my_array = np.array([1, 2, 3])
my_array

array([1, 2, 3])

**PyTorch:** tensors are created the same way, using `torch.tensor`.

**PyTorch:** tensor được tạo theo cách tương tự, sử dụng `torch.tensor`.

In [7]:
# PyTorch
my_tensor = torch.tensor([1, 2, 3])
my_tensor

tensor([1, 2, 3])

### 2.2 Multi-dimensional / Mảng đa chiều

Both libraries support arrays/tensors of arbitrary dimension. For example, we can create two-dimensional arrays (e.g. to store a matrix) as follows:

Cả hai thư viện đều hỗ trợ mảng/tensor với số chiều tùy ý. Ví dụ, chúng ta có thể tạo mảng hai chiều (chẳng hạn để lưu trữ ma trận) như sau:

In [8]:
# NumPy
my_2d_array = np.array([[1, 2, 3], [4, 5, 6]])
print("NumPy:\n", my_2d_array)

# PyTorch
my_2d_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("\nPyTorch:\n", my_2d_tensor)

NumPy:
 [[1 2 3]
 [4 5 6]]

PyTorch:
 tensor([[1, 2, 3],
        [4, 5, 6]])


### 2.3 Accessing elements / Truy cập phần tử

We can access individual elements using two indices — the syntax is **identical** in both libraries.

Chúng ta có thể truy cập từng phần tử bằng hai chỉ số — cú pháp **giống hệt nhau** trong cả hai thư viện.

In [ ]:
# NumPy
print("NumPy [1, 2]:", my_2d_array[1, 2])

# PyTorch
print("PyTorch [1, 2]:", my_2d_tensor[1, 2])

We can also access rows and columns — again, identical syntax:

Chúng ta cũng có thể truy cập hàng và cột — cú pháp một lần nữa giống hệt:

In [ ]:
# NumPy
print("NumPy row 1:", my_2d_array[1])
print("NumPy column 2:", my_2d_array[:, 2])

# PyTorch
print("PyTorch row 1:", my_2d_tensor[1])
print("PyTorch column 2:", my_2d_tensor[:, 2])

### 2.4 Shape and dtype / Hình dạng và kiểu dữ liệu

Both arrays and tensors have a `shape` attribute.

Cả mảng và tensor đều có thuộc tính `shape`.

In [ ]:
# NumPy
print("NumPy shape:", my_array.shape, my_2d_array.shape)

# PyTorch
print("PyTorch shape:", my_tensor.shape, my_2d_tensor.shape)

Unlike Python lists, both NumPy arrays and PyTorch tensors must have a single data type — all elements must share that type. The main types are `int32`, `int64`, `float32`, and `float64`.

Khác với danh sách Python, cả mảng NumPy và tensor PyTorch đều phải có một kiểu dữ liệu duy nhất — tất cả phần tử phải cùng kiểu. Các kiểu chính bao gồm `int32`, `int64`, `float32`, và `float64`.

In [ ]:
# NumPy
print("NumPy dtype:", my_array.dtype)

# PyTorch
print("PyTorch dtype:", my_tensor.dtype)

The `dtype` can be specified when creating the array/tensor:

Kiểu dữ liệu `dtype` có thể được chỉ định khi tạo mảng/tensor:

In [ ]:
# NumPy
my_float_array = np.array([1, 2, 3], dtype=np.float64)
print("NumPy dtype:", my_float_array.dtype)

# PyTorch
my_float_tensor = torch.tensor([1, 2, 3], dtype=torch.float64)
print("PyTorch dtype:", my_float_tensor.dtype)

### 2.5 Zeros, ones, arange, linspace, reshape

We can create arrays/tensors of all zeros using `zeros`:

Chúng ta có thể tạo mảng/tensor chứa toàn số 0 bằng `zeros`:

In [ ]:
# NumPy
zero_array = np.zeros((2, 3))
print("NumPy zeros:\n", zero_array)

# PyTorch
zero_tensor = torch.zeros((2, 3))
print("PyTorch zeros:\n", zero_tensor)

Similarly for ones, arange, and linspace — all have the same names:

Tương tự cho ones, arange, và linspace — tất cả đều có cùng tên gọi:

In [ ]:
# NumPy
print("NumPy arange(5):     ", np.arange(5))
print("NumPy arange(3, 5):  ", np.arange(3, 5))
print("NumPy linspace(0,1,10):", np.linspace(0, 1, 10))

# PyTorch — identical API
print("\nPyTorch arange(5):     ", torch.arange(5))
print("PyTorch arange(3, 5):  ", torch.arange(3, 5))
print("PyTorch linspace(0,1,10):", torch.linspace(0, 1, 10))

`reshape` is another important operation for changing the shape of an array/tensor:

`reshape` là một thao tác quan trọng khác để thay đổi hình dạng của mảng/tensor:

In [ ]:
# NumPy
my_vec = np.array([1, 2, 3, 4, 5, 6])
print("NumPy reshape (2,3):\n", my_vec.reshape(2, 3))

# PyTorch — identical syntax
my_vec_t = torch.tensor([1, 2, 3, 4, 5, 6])
print("PyTorch reshape (2,3):\n", my_vec_t.reshape(2, 3))

### 2.6 NumPy ↔ PyTorch conversion / Chuyển đổi qua lại

You can convert between NumPy arrays and PyTorch tensors seamlessly. They will **share the same underlying memory**, so changes to one affect the other.

Bạn có thể chuyển đổi qua lại giữa mảng NumPy và tensor PyTorch một cách liền mạch. Chúng sẽ **chia sẻ cùng một vùng nhớ nền**, vì vậy thay đổi ở một bên sẽ ảnh hưởng đến bên kia.

In [ ]:
np_arr = np.array([1.0, 2.0, 3.0])
pt_tensor = torch.from_numpy(np_arr)    # NumPy → PyTorch
print("PyTorch tensor:", pt_tensor)

back_to_np = pt_tensor.numpy()           # PyTorch → NumPy
print("Back to NumPy:", back_to_np)

Play with these operations and make sure you understand them well.

Hãy thử nghiệm với những thao tác này và đảm bảo rằng bạn hiểu chúng rõ ràng.

## 3. Basic operations / Các phép toán cơ bản

In both NumPy and PyTorch, we express computations directly over arrays/tensors. This makes code much more succinct and much faster than using Python for loops.

Trong cả NumPy và PyTorch, chúng ta thực hiện các phép tính trực tiếp trên mảng/tensor. Điều này giúp code ngắn gọn hơn và nhanh hơn rất nhiều so với việc dùng vòng lặp Python.

Arithmetic operations can be performed directly. For instance, adding two arrays/tensors:

Các phép toán số học có thể được thực hiện trực tiếp. Ví dụ, cộng hai mảng/tensor:

In [ ]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

# NumPy
print("NumPy a + b:", array_a + array_b)

# PyTorch — identical syntax
print("PyTorch a + b:", tensor_a + tensor_b)

Compare this with the equivalent computation using a for loop:

Hãy so sánh với cách tính tương đương sử dụng vòng lặp for:

In [ ]:
# Slow, verbose for-loop (works for both NumPy and PyTorch — but don't do this!)
array_out = np.zeros_like(array_a)
for i in range(len(array_a)):
    array_out[i] = array_a[i] + array_b[i]
print("For-loop result:", array_out)

Not only is the for-loop code more verbose, it will also run much more slowly — and cannot take advantage of GPU acceleration in PyTorch.

Đoạn code vòng lặp for không những dài dòng hơn mà còn chạy chậm hơn rất nhiều — và không thể tận dụng tăng tốc GPU trong PyTorch.

### 3.1 Element-wise functions / Hàm theo từng phần tử

Mathematical functions like `sin` operate element-wise. Both `np.sin` and `torch.sin` work the same way:

Các hàm toán học như `sin` hoạt động trên từng phần tử. Cả `np.sin` và `torch.sin` đều hoạt động giống nhau:

In [ ]:
# NumPy
print("NumPy sin:", np.sin(array_a))

# PyTorch — note: sin requires float input
print("PyTorch sin:", torch.sin(tensor_a.float()))

### 3.2 Matrix multiplication / Phép nhân ma trận

Vector inner product and matrix multiplication: NumPy uses `np.dot`, while PyTorch uses `torch.matmul`. Both also support the `@` operator.

Tích trong của vectơ và phép nhân ma trận: NumPy dùng `np.dot`, trong khi PyTorch dùng `torch.matmul`. Cả hai đều hỗ trợ toán tử `@`.

In [ ]:
array_A = np.random.rand(5, 3)
array_B = np.random.randn(3, 4)
tensor_A = torch.rand(5, 3)
tensor_B = torch.randn(3, 4)

# NumPy
print("NumPy dot shape:", np.dot(array_A, array_B).shape)

# PyTorch
print("PyTorch matmul shape:", torch.matmul(tensor_A, tensor_B).shape)

# Both support the @ operator
print("NumPy @ shape:", (array_A @ array_B).shape)
print("PyTorch @ shape:", (tensor_A @ tensor_B).shape)

### 3.3 Matrix transpose / Chuyển vị ma trận

Matrix transpose uses `.transpose()` or `.T` — identical in both libraries:

Chuyển vị ma trận sử dụng `.transpose()` hoặc `.T` — giống hệt trong cả hai thư viện:

In [ ]:
# NumPy
print("NumPy A.T shape:", array_A.T.shape)

# PyTorch
print("PyTorch A.T shape:", tensor_A.T.shape)

### 3.4  inverse matrix/ Nghịch đảo ma trận

Inverse matrix use np.linalg.inv(A) for numpy and torch.linalg.inv(A) for pytorch

Nghịch đảo ma trận mình sử dụng np.linal.inv cho numpy và torch.linal.inv(A) cho pytorch

In [ ]:
#Create a square matrix A
A = np.array([[1.0, 2.0], 
              [3.0, 4.0]])

#Calculate the inverse of matrix A
A_inv = np.linalg.inv(A)
print("Inverse matrix of A in NumPy:\n", A_inv)

In [ ]:
#Create a square matrix A
A_tensor = torch.tensor([[1.0, 2.0], 
                         [3.0, 4.0]])

# Calculate the inverse of matrix A
A_tensor_inv = torch.linalg.inv(A_tensor)
print("Inverse matrix of A in PyTorch:\n", A_tensor_inv)


## 4. Slicing and masking / Cắt và lọc dữ liệu

Like Python lists, both NumPy arrays and PyTorch tensors support slicing — the syntax is **exactly the same**.

Giống như danh sách Python, cả mảng NumPy và tensor PyTorch đều hỗ trợ cắt (slicing) — cú pháp **giống hệt nhau**.

In [ ]:
# NumPy
print("NumPy [5:]:", np.arange(10)[5:])

# PyTorch
print("PyTorch [5:]:", torch.arange(10)[5:])

We can also select only certain elements using boolean masking:

Chúng ta cũng có thể chọn những phần tử nhất định bằng mặt nạ boolean:

In [ ]:
# NumPy
x_np = np.arange(10)
mask_np = x_np >= 5
print("NumPy masked:", x_np[mask_np])

# PyTorch
x_pt = torch.arange(10)
mask_pt = x_pt >= 5
print("PyTorch masked:", x_pt[mask_pt])

## 5. GPU Acceleration / Tăng tốc GPU (PyTorch)

One of PyTorch's biggest advantages over NumPy is **GPU acceleration**. NumPy runs only on CPU; PyTorch tensors can be moved to a GPU with a single method call.

Một trong những lợi thế lớn nhất của PyTorch so với NumPy là **tăng tốc GPU**. NumPy chỉ chạy trên CPU; tensor PyTorch có thể được di chuyển lên GPU chỉ với một lời gọi phương thức.

In [ ]:
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU name: {torch.cuda.get_device_name(0)}")
else:
    print("No GPU detected — tensors will stay on CPU.")

Moving a tensor to GPU (and back):

Di chuyển tensor lên GPU (và trở lại):

In [ ]:
tensor_cpu = torch.rand(1000, 1000)
if torch.cuda.is_available():
    tensor_gpu = tensor_cpu.to('cuda')   # CPU → GPU
    print(f"Device: {tensor_gpu.device}")
    tensor_back = tensor_gpu.to('cpu')    # GPU → CPU
    print(f"Back to: {tensor_back.device}")
else:
    print("GPU not available — skipping.")

**Why does this matter?** For large matrices, GPU operations can be 10–100× faster than CPU. **Important:** You can only perform operations between tensors on the same device. Mixing CPU and GPU tensors will cause an error.

**Tại sao điều này quan trọng?** Với các ma trận lớn, tính toán trên GPU có thể nhanh hơn CPU từ 10–100 lần. **Quan trọng:** Bạn chỉ có thể thực hiện phép toán giữa các tensor trên cùng một thiết bị. Trộn tensor CPU và GPU sẽ gây ra lỗi.

## 6. Exercises / Bài tập

**For each exercise, you must provide a solution using BOTH NumPy AND PyTorch.** This will help you see the similarities and differences firsthand.

**Với mỗi bài tập, bạn phải cung cấp lời giải bằng CẢ NumPy VÀ PyTorch.** Điều này sẽ giúp bạn trực tiếp thấy được sự tương đồng và khác biệt.

---

**Exercise 1.** Create a 3D array/tensor of shape (2, 2, 2) containing 8 values. Access individual elements and slices. Write the code for **both** NumPy and PyTorch.

**Bài 1.** Tạo một mảng/tensor 3D có kích thước (2, 2, 2) chứa 8 giá trị. Truy cập từng phần tử riêng lẻ và thực hiện cắt lát. Viết code cho **cả** NumPy và PyTorch.

In [ ]:
# NumPy solution

# PyTorch solution

---

**Exercise 2.** Implement the ReLU activation function (ReLU(x) = max(0, x)) using `np.maximum` for NumPy and `torch.maximum` for PyTorch. Test both on a single value and on an array/tensor of values.

**Bài 2.** Triển khai hàm kích hoạt ReLU (ReLU(x) = max(0, x)) sử dụng `np.maximum` cho NumPy và `torch.maximum` cho PyTorch. Kiểm tra cả hai với một giá trị đơn lẻ và một mảng/tensor giá trị.

In [ ]:
# NumPy
def relu_numpy(x):
    return

# Test
print(relu_numpy(np.array([1, -3, 2.5])))

# PyTorch
def relu_pytorch(x):
    return

# Test
print(relu_pytorch(torch.tensor([1.0, -3.0, 2.5])))

---

**Exercise 3.** Write a function that computes the Euclidean norm (L2 norm) of a 1D vector using **both** NumPy (without for loops) and PyTorch. Hint: use `sqrt` and `sum` (or `.sum()`).

**Bài 3.** Viết một hàm tính chuẩn Euclid (L2 norm) của một vectơ 1D bằng **cả** NumPy (không dùng vòng lặp for) và PyTorch. Gợi ý: sử dụng `sqrt` và `sum` (hoặc `.sum()`).

In [ ]:
# NumPy
def euclidean_norm_numpy(x):
    return

my_vector_np = np.array([0.5, -1.2, 3.3, 4.5])
print("NumPy:", euclidean_norm_numpy(my_vector_np))

# PyTorch
def euclidean_norm_pytorch(x):
    return

my_vector_pt = torch.tensor([0.5, -1.2, 3.3, 4.5])
print("PyTorch:", euclidean_norm_pytorch(my_vector_pt))

---

**Exercise 4.** Write a function that computes the Euclidean norms of each row in a 2D matrix using **both** NumPy and PyTorch. Hint: NumPy uses `axis`; PyTorch uses `dim` — they mean the same thing.

**Bài 4.** Viết một hàm tính chuẩn Euclid của từng hàng trong một ma trận 2D bằng **cả** NumPy và PyTorch. Gợi ý: NumPy dùng `axis`; PyTorch dùng `dim` — chúng có cùng ý nghĩa.

In [ ]:
# NumPy
def euclidean_norm_2d_numpy(X):
    return

my_matrix_np = np.array([[0.5, -1.2, 4.5],
                          [-3.2, 1.9, 2.7]])
print("NumPy:", euclidean_norm_2d_numpy(my_matrix_np))

# PyTorch
def euclidean_norm_2d_pytorch(X):
    return

my_matrix_pt = torch.tensor([[0.5, -1.2, 4.5],
                              [-3.2, 1.9, 2.7]])
print("PyTorch:", euclidean_norm_2d_pytorch(my_matrix_pt))

---

**Exercise 5 (NumPy).** Compute the mean value of the features in the [iris dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html). Hint: use the `axis` argument on `np.mean`.

**Bài 5 (NumPy).** Tính giá trị trung bình của các đặc trưng trong tập dữ liệu [iris](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html). Gợi ý: sử dụng đối số `axis` của `np.mean`.

In [ ]:
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)

# NumPy: compute mean of each feature (result should be an array of size 4)

# PyTorch: convert X to a tensor and compute mean using dim=0

## 7. Going further / Tìm hiểu thêm

**NumPy resources:**
* NumPy [reference](https://numpy.org/doc/stable/reference/)
* SciPy [lectures](https://scipy-lectures.org/)
* One-hour [tutorial](https://www.youtube.com/watch?v=QUT1VHiLmmI) on YouTube

**PyTorch resources:**
* PyTorch [official documentation](https://pytorch.org/docs/stable/)
* Deep Learning with PyTorch: A 60 Minute Blitz [tutorial](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)
* [Video tutorial](https://www.youtube.com/watch?v=GIsg-ZUy0MY) by freeCodeCamp

**Tài nguyên NumPy:**
* [Tham khảo](https://numpy.org/doc/stable/reference/) NumPy
* [Bài giảng](https://scipy-lectures.org/) SciPy
* [Hướng dẫn](https://www.youtube.com/watch?v=QUT1VHiLmmI) một giờ trên YouTube

**Tài nguyên PyTorch:**
* [Tài liệu chính thức](https://pytorch.org/docs/stable/) của PyTorch
* Deep Learning với PyTorch: Hướng dẫn 60 Phút [cấp tốc](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)
* [Hướng dẫn video](https://www.youtube.com/watch?v=GIsg-ZUy0MY) bởi freeCodeCamp

# Matplotlib

## Basic plots / Biểu đồ cơ bản

Matplotlib is a plotting library for Python.

We start with a rudimentary plotting example.

Matplotlib là một thư viện vẽ biểu đồ trong Python.

Chúng ta bắt đầu với một ví dụ đơn giản về vẽ biểu đồ.

In [ ]:
from matplotlib import pyplot as plt

x_values = np.linspace(-3, 3, 100)

plt.figure()
plt.plot(x_values, np.sin(x_values), label="Sinusoid")
plt.xlabel("x")
plt.ylabel("sin(x)")
plt.title("Matplotlib example")
plt.legend(loc="upper left")
plt.show()

We continue with a rudimentary scatter plot example. This example displays samples from the [iris dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html) using the first two features. Colors indicate class membership (there are 3 classes).

Chúng ta tiếp tục với một ví dụ đơn giản về biểu đồ phân tán (scatter plot).

Ví dụ này hiển thị các mẫu từ tập dữ liệu Iris, sử dụng hai đặc trưng đầu tiên. Màu sắc biểu thị nhóm phân loại (có tổng cộng 3 nhóm).

In [ ]:
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)

X_class0 = X[y == 0]
X_class1 = X[y == 1]
X_class2 = X[y == 2]

plt.figure()
plt.scatter(X_class0[:, 0], X_class0[:, 1], label="Class 0", color="C0")
plt.scatter(X_class1[:, 0], X_class1[:, 1], label="Class 1", color="C1")
plt.scatter(X_class2[:, 0], X_class2[:, 1], label="Class 2", color="C2")
plt.show()

We see that samples belonging to class 0 can be linearly separated from the rest using only the first two features.

Chúng ta có thể thấy rằng các mẫu thuộc lớp 0 có thể được phân tách tuyến tính khỏi các lớp còn lại chỉ bằng hai đặc trưng đầu tiên.

## Exercises / Bài tập


**Exercise 1.** Plot the relu and the [softplus](https://en.wikipedia.org/wiki/Rectifier_(neural_networks)#Softplus) functions on the same graph.

**Bài 1:** Vẽ đồ thị của hai hàm ReLU và [softplus](https://en.wikipedia.org/wiki/Rectifier_(neural_networks)#Softplus) trên cùng một biểu đồ.

What is the main difference between the two functions?

Sự khác biệt chính giữa hai hàm này là gì?

**Exercise 2.** Repeat the same scatter plot but using the [digits dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_digits.html) instead.

**Bài 2:** Lặp lại biểu đồ phân tán như đã làm với tập dữ liệu Iris, nhưng lần này sử dụng tập dữ liệu [Digits](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_digits.html).

Are pixel values good features for classifying samples?

Các giá trị pixel có phải là đặc trưng tốt để phân loại mẫu không?

**Exercise 3.** Draw a simple line plot
Use Matplotlib to draw a line plot showing the average temperature over 5 consecutive days in a week. The temperature data is as follows:
- Day 1: 28°C
- Day 2: 30°C
- Day 3: 29°C
- Day 4: 31°C
- Day 5: 27°C

Requirements:
- The x-axis represents the days (1, 2, 3, 4, 5).
- The y-axis represents the temperature (°C).
- Label the x-axis as "Day" and the y-axis as "Temperature (°C)".
- Set the title as "Temperature Over 5 Days".
- Use a red line.

**Bài 3:** Sử dụng Matplotlib để vẽ biểu đồ đường thể hiện nhiệt độ trung bình của 5 ngày liên tiếp trong tuần. Dữ liệu nhiệt độ như sau:
- Ngày 1: 28°C
- Ngày 2: 30°C
- Ngày 3: 29°C
- Ngày 4: 31°C
- Ngày 5: 27°C

Yêu cầu:
- Trục x là các ngày (1, 2, 3, 4, 5).
- Trục y là nhiệt độ (°C).
- Đặt nhãn trục x là "Ngày", trục y là "Nhiệt độ (°C)".
- Đặt tiêu đề là "Nhiệt độ trong 5 ngày".
- Vẽ đường màu đỏ.

## Going further

*  Official [tutorial](https://matplotlib.org/tutorials/introductory/pyplot.html)
* [Tutorial](https://www.youtube.com/watch?v=qErBw-R2Ybk) on Youtube

* [Hướng dẫn](https://matplotlib.org/tutorials/introductory/pyplot.html) chính thức
* [Hướng dẫn](https://www.youtube.com/watch?v=qErBw-R2Ybk) trên Youtube